name: Flatpak Builder

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_native_flatpak:
    name: Build Flatpak
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Builder Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/flatpak
            .flatpak-builder
          key: flatpak-x86_64-${{ github.sha }}
          restore-keys: |
            flatpak

      - name: Setup Dependencies
        run: |
          sudo apt update -y
          sudo apt install flatpak -y
          sudo su $(whoami) -c 'flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo'
          sudo su $(whoami) -c 'flatpak install flathub org.flatpak.Builder -y'

      - name: Build Flatpak
        run: |
          git clone --depth 1 -b add-org.jellyfin.JellyfinServer.Plugin.IntelComputeRuntime https://github.com/istori1/flathub.git source
          sudo su $(whoami) -c '
            flatpak run org.flatpak.Builder --user --repo=local_repo --install-deps-from=flathub \
            --force-clean --default-branch=test build $(ls -1 source/*.yml)
          '

      - name: Bundle Flatpak
        env:
          FLATPAK_ID: org.jellyfin.JellyfinServer.Plugin.IntelComputeRuntime
        run: |
          mkdir artifacts
          flatpak repo --branches local_repo
          # flatpak build-bundle local_repo artifacts/$FLATPAK_ID_$(uname -m).flatpak $FLATPAK_ID test
          flatpak build-bundle --runtime local_repo artifacts/$FLATPAK_ID_$(uname -m).flatpak $FLATPAK_ID 1

      - name: Upload Flatpak Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flatpak-bundle
          path: artifacts
