name: Flatpak Builder

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build_native_flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    env:
      FLATPAK_ID: com.dec05eba.gpu_screen_recorder
      FLATPAK_MANIFEST: com.dec05eba.gpu_screen_recorder.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Builder Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/flatpak
            .flatpak-builder
          key: flatpak-x86_64-${{ github.sha }}
          restore-keys: |
            flatpak

      - name: Get Git Source
        env:
          URL: https://github.com/flathub/com.dec05eba.gpu_screen_recorder.git
          COMMIT: 7037f8e9de7f32af61dfbbcb2bf3d5dd505f5e35
        run: |
          mkdir src
          git clone --depth 1 --recursive ${URL} src
          cd src && git reset --hard ${COMMIT}

      - name: Setup Dependencies
        run: |
          sudo apt update -y
          sudo apt install flatpak yamllint -y
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo su $(whoami) -c 'flatpak install flathub org.flatpak.Builder org.flathub.flatpak-external-data-checker -y'

      - name: YAML Lint
        if: false
        run: yamllint src/${FLATPAK_MANIFEST}

      - name: External Data Checker
        run: flatpak run org.flathub.flatpak-external-data-checker src/${FLATPAK_MANIFEST}

      - name: Build Flatpak
        run: |
          echo ${FLATPAK_MANIFEST} > MANIFEST.txt
          sudo su $(whoami) -c '
            FLATPAK_MANIFEST=$(cat MANIFEST.txt)

            flatpak run org.flatpak.Builder --user --repo=local_repo --install-deps-from=flathub \
            --force-clean --default-branch=test build src/${FLATPAK_MANIFEST}
          '

      - name: Bundle Flatpak
        run: |
          mkdir artifacts
          flatpak repo --branches local_repo
          flatpak build-bundle local_repo artifacts/${FLATPAK_ID}_$(uname -m).flatpak ${FLATPAK_ID} test
          # flatpak build-bundle --runtime local_repo artifacts/${FLATPAK_ID}_Debug_$(uname -m).flatpak ${FLATPAK_ID}.Debug test

      - name: Upload Flatpak Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flatpak-bundle
          path: artifacts
